# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"State": "00_State.ipynb",
         "get_dataset": "00_State.ipynb",
         "ChessValueDataset": "00_State.ipynb",
         "chess_dataset": "00_State.ipynb",
         "train_loader": "00_State.ipynb",
         "Valuator": "00_State.ipynb",
         "explore_leaves": "00_State.ipynb",
         "computer_move": "00_State.ipynb",
         "move": "00_State.ipynb",
         "s": "00_State.ipynb",
         "v": "00_State.ipynb",
         "quit": "00_State.ipynb"}

modules = ["core.py"]

doc_url = "https://svenssona.github.io/mediocre_chess_ai/"

git_url = "https://github.com/svenssona/mediocre_chess_ai/tree/{branch}/"

def custom_doc_links(name): return None
