# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"State": "00_state.ipynb",
         "get_dataset": "01_generate_training_set.ipynb",
         "ChessValueDataset": "02_train.ipynb",
         "Net": "02_train.ipynb",
         "Valuator": "03_play.ipynb",
         "ClassicValuator": "03_play.ipynb",
         "MAXVAL": "03_play.ipynb",
         "explore_leaves": "03_play.ipynb",
         "computer_move": "03_play.ipynb",
         "move": "03_play.ipynb",
         "computer_minimax": "03_play.ipynb"}

modules = ["state.py",
           "generate_training_set.py",
           "train.py",
           "play.py"]

doc_url = "https://svenssona.github.io/mediocre_chess_ai/"

git_url = "https://github.com/svenssona/mediocre_chess_ai/tree/master/"

def custom_doc_links(name): return None
